version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: db_atividade4
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./carga.sql:/docker-entrypoint-initdb.d/carga.sql

  app:
    build: .
    ports:
      - "3030:3000"
    depends_on:
      - db

volumes:
  db_data:
